-- ════════════════════════════════════════════════════════════════════════════
-- Mensa-Ranking v1 – im SQL Editor des separaten Mensa-Supabase-Projekts ausführen.
-- Idempotent und nur additiv: legt ausschließlich mensa_*-Objekte und den Bucket
-- „mensa-photos“ an bzw. aktualisiert sie. Löscht keine Tabellen und keine Daten.
--
-- Rechte-Modell (alles serverseitig):
--   • Lesen und Schreiben nur für Mitglieder (Tabelle mensa_members) – ein bloßer
--     Login reicht nicht. anon hat auf keine Tabelle Zugriff.
--   • Genau eine Stimme pro Person und Ausgabe (Primärschlüssel), Note 1–10.
--   • Einzelstimmen sieht nur die Person selbst; alle anderen nur Anzahl und Schnitt.
--   • Einträge: Ersteller:in 15 Minuten lang, Admin jederzeit.
-- ════════════════════════════════════════════════════════════════════════════
begin;

-- ── 1. Hilfsfunktionen ──────────────────────────────────────────────────────
-- „Heute“ in Heidelberg, nicht in UTC.
create or replace function public.mensa_today()
returns date
language sql
stable
set search_path = ''
as $$ select (now() at time zone 'Europe/Berlin')::date $$;

-- Vergleichsschlüssel für Gerichtsnamen. Nur bei exakt gleichem Schlüssel gilt ein
-- Name als dasselbe Gericht (Groß/klein, Umlaut-Schreibweise, Akzente, Satzzeichen,
-- Leerzeichen). Ähnliche Namen werden nie automatisch zusammengelegt.
-- Muss mit nameKey() in assets/mensa/logic.js übereinstimmen (siehe _tests/mensa).
create or replace function public.mensa_name_key(name text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select btrim(regexp_replace(lower(translate(
    replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(
      normalize(coalesce(name, ''), NFC),
      'Ä', 'ae'), 'ä', 'ae'), 'Ö', 'oe'), 'ö', 'oe'), 'Ü', 'ue'), 'ü', 'ue'),
      'ß', 'ss'), 'ẞ', 'ss'), 'Æ', 'ae'), 'æ', 'ae'),
    'ÁÀÂÃÅáàâãåÉÈÊËéèêëÍÌÎÏíìîïÓÒÔÕØóòôõøÚÙÛúùûÇçÑñ',
    'AAAAAaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUuuuCcNn')),
    '[^a-z0-9]+', ' ', 'g'))
$$;

-- ── 2. Tabellen ─────────────────────────────────────────────────────────────
-- Wer zur Gruppe gehört. Pflege nur über SQL Editor / Dashboard (keine Schreib-Policy).
create table if not exists public.mensa_members (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 40),
  is_admin     boolean not null default false,
  created_at   timestamptz not null default now()
);

create table if not exists public.mensa_canteens (
  id           integer generated by default as identity primary key,
  name         text not null unique check (char_length(btrim(name)) between 1 and 80),
  openmensa_id integer,
  active       boolean not null default true
);

-- Das allgemeine Gericht (kommt ggf. immer wieder).
create table if not exists public.mensa_dishes (
  id         bigint generated by default as identity primary key,
  name       text not null check (char_length(btrim(name)) between 2 and 120),
  name_key   text generated always as (public.mensa_name_key(name)) stored,
  created_by uuid default auth.uid() references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint mensa_dishes_name_key_unique unique (name_key),
  constraint mensa_dishes_name_key_not_empty check (public.mensa_name_key(name) <> '')
);

-- Die konkrete Ausgabe eines Gerichts an einem Tag in einer Mensa.
create table if not exists public.mensa_servings (
  id          bigint generated by default as identity primary key,
  dish_id     bigint not null references public.mensa_dishes (id) on delete restrict,
  canteen_id  integer not null references public.mensa_canteens (id) on delete restrict,
  served_on   date not null default public.mensa_today(),
  price_cents integer check (price_cents between 0 and 5000),
  note        text check (char_length(note) <= 200),
  photo_path  text,
  thumb_path  text,
  created_by  uuid default auth.uid() references auth.users (id) on delete set null,
  created_at  timestamptz not null default now(),
  -- wird bei jeder Stimme berührt → Live-Update für alle offenen Seiten
  activity_at timestamptz not null default now(),
  -- Gleiches Gericht, gleiche Mensa, gleicher Tag nur einmal; verschiedene Gerichte beliebig.
  constraint mensa_servings_once_per_day unique (dish_id, canteen_id, served_on),
  constraint mensa_servings_photo_pair check ((photo_path is null) = (thumb_path is null))
);
create index if not exists mensa_servings_served_on_idx on public.mensa_servings (served_on desc);

-- Eine Stimme pro Person und Ausgabe. filling = subjektiver Sättigungs-Eindruck
-- (1 eher leicht, 2 sättigend, 3 sehr sättigend) – kein Messwert, getrennt von der Note.
create table if not exists public.mensa_votes (
  serving_id bigint not null references public.mensa_servings (id) on delete cascade,
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  rating     smallint not null check (rating between 1 and 10),
  filling    smallint check (filling between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (serving_id, user_id)
);

-- ── 3. Rollen-Prüfung ───────────────────────────────────────────────────────
create or replace function public.mensa_is_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$ select exists (select 1 from public.mensa_members where user_id = auth.uid()) $$;

create or replace function public.mensa_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$ select exists (select 1 from public.mensa_members where user_id = auth.uid() and is_admin) $$;

-- Für die Seite: bin ich Mitglied/Admin, wie heiße ich?
create or replace function public.mensa_me()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select jsonb_build_object('member', true, 'admin', m.is_admin, 'name', m.display_name)
       from public.mensa_members m where m.user_id = auth.uid()),
    jsonb_build_object('member', false, 'admin', false, 'name', null))
$$;

-- ── 4. Trigger ──────────────────────────────────────────────────────────────
-- Ersteller:in und Zeitstempel sind nach dem Anlegen fest; Fotos nur über mensa_set_photo().
-- current_user ist in security-definer-Funktionen deren Besitzer, dort greift die Sperre nicht.
create or replace function public.mensa_servings_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if current_user in ('anon', 'authenticated') then
    if new.photo_path is distinct from old.photo_path or new.thumb_path is distinct from old.thumb_path then
      raise exception 'Fotos bitte über mensa_set_photo() ändern' using errcode = '42501';
    end if;
    new.created_by := old.created_by;
    new.created_at := old.created_at;
  end if;
  return new;
end $$;

drop trigger if exists mensa_servings_guard on public.mensa_servings;
create trigger mensa_servings_guard before update on public.mensa_servings
  for each row execute function public.mensa_servings_guard();

create or replace function public.mensa_votes_set_updated()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  new.created_at := old.created_at;
  return new;
end $$;

drop trigger if exists mensa_votes_set_updated on public.mensa_votes;
create trigger mensa_votes_set_updated before update on public.mensa_votes
  for each row execute function public.mensa_votes_set_updated();

-- Jede Stimme berührt die Ausgabe → alle Mitglieder bekommen ein Realtime-Update,
-- ohne dass Einzelstimmen anderer sichtbar werden.
create or replace function public.mensa_votes_touch_serving()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.mensa_servings set activity_at = now()
   where id = coalesce(new.serving_id, old.serving_id);
  return null;
end $$;

drop trigger if exists mensa_votes_touch_serving on public.mensa_votes;
create trigger mensa_votes_touch_serving after insert or update or delete on public.mensa_votes
  for each row execute function public.mensa_votes_touch_serving();

-- ── 5. Zugriffsrechte (Row Level Security) ─────────────────────────────────
alter table public.mensa_members  enable row level security;
alter table public.mensa_canteens enable row level security;
alter table public.mensa_dishes   enable row level security;
alter table public.mensa_servings enable row level security;
alter table public.mensa_votes    enable row level security;

-- Nicht angemeldete Besucher: gar kein Zugriff (zusätzlich zu RLS).
revoke all on table public.mensa_members, public.mensa_canteens, public.mensa_dishes,
                    public.mensa_servings, public.mensa_votes from anon;
-- TRUNCATE umgeht RLS – niemandem außer dem Besitzer erlauben.
revoke truncate, references, trigger on table public.mensa_members, public.mensa_canteens,
       public.mensa_dishes, public.mensa_servings, public.mensa_votes from authenticated;

-- Nur Policies mit genau diesen Namen werden ersetzt.
drop policy if exists "mensa members read"   on public.mensa_members;
drop policy if exists "mensa canteens read"  on public.mensa_canteens;
drop policy if exists "mensa dishes read"    on public.mensa_dishes;
drop policy if exists "mensa dishes insert"  on public.mensa_dishes;
drop policy if exists "mensa dishes update"  on public.mensa_dishes;
drop policy if exists "mensa dishes delete"  on public.mensa_dishes;
drop policy if exists "mensa servings read"   on public.mensa_servings;
drop policy if exists "mensa servings insert" on public.mensa_servings;
drop policy if exists "mensa servings update" on public.mensa_servings;
drop policy if exists "mensa servings delete" on public.mensa_servings;
drop policy if exists "mensa votes read own"   on public.mensa_votes;
drop policy if exists "mensa votes insert own" on public.mensa_votes;
drop policy if exists "mensa votes update own" on public.mensa_votes;
drop policy if exists "mensa votes delete own" on public.mensa_votes;

-- Mitglieder & Mensen: lesen nur Mitglieder, schreiben nur über den SQL Editor.
create policy "mensa members read" on public.mensa_members for select to authenticated
  using ((select public.mensa_is_member()));
create policy "mensa canteens read" on public.mensa_canteens for select to authenticated
  using ((select public.mensa_is_member()));

-- Gerichte: Mitglieder lesen und legen an; umbenennen/löschen nur Admin.
create policy "mensa dishes read" on public.mensa_dishes for select to authenticated
  using ((select public.mensa_is_member()));
create policy "mensa dishes insert" on public.mensa_dishes for insert to authenticated
  with check ((select public.mensa_is_member()) and created_by = (select auth.uid()));
create policy "mensa dishes update" on public.mensa_dishes for update to authenticated
  using ((select public.mensa_is_admin())) with check ((select public.mensa_is_admin()));
create policy "mensa dishes delete" on public.mensa_dishes for delete to authenticated
  using ((select public.mensa_is_admin()));

-- Ausgaben: Mitglieder lesen und tragen ein (nicht in der Zukunft, Foto erst danach);
-- ändern/löschen: Ersteller:in 15 Minuten lang, Admin immer.
create policy "mensa servings read" on public.mensa_servings for select to authenticated
  using ((select public.mensa_is_member()));
create policy "mensa servings insert" on public.mensa_servings for insert to authenticated
  with check (
    (select public.mensa_is_member())
    and created_by = (select auth.uid())
    and served_on <= public.mensa_today()
    and photo_path is null and thumb_path is null
  );
create policy "mensa servings update" on public.mensa_servings for update to authenticated
  using (
    (select public.mensa_is_admin())
    or ((select public.mensa_is_member()) and created_by = (select auth.uid()) and created_at > now() - interval '15 minutes')
  )
  with check (
    served_on <= public.mensa_today()
    and ((select public.mensa_is_admin())
         or ((select public.mensa_is_member()) and created_by = (select auth.uid())))
  );
create policy "mensa servings delete" on public.mensa_servings for delete to authenticated
  using (
    (select public.mensa_is_admin())
    or ((select public.mensa_is_member()) and created_by = (select auth.uid()) and created_at > now() - interval '15 minutes')
  );

-- Stimmen: nur die eigene Zeile – lesen, abgeben, ändern, zurückziehen.
-- Bewerten nur für Ausgaben bis heute (nicht für eingetragene Zukunftstermine).
create policy "mensa votes read own" on public.mensa_votes for select to authenticated
  using (user_id = (select auth.uid()) and (select public.mensa_is_member()));
create policy "mensa votes insert own" on public.mensa_votes for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and (select public.mensa_is_member())
    and exists (select 1 from public.mensa_servings s where s.id = serving_id and s.served_on <= public.mensa_today())
  );
create policy "mensa votes update own" on public.mensa_votes for update to authenticated
  using (user_id = (select auth.uid()) and (select public.mensa_is_member()))
  with check (user_id = (select auth.uid()) and (select public.mensa_is_member()));
create policy "mensa votes delete own" on public.mensa_votes for delete to authenticated
  using (user_id = (select auth.uid()) and (select public.mensa_is_member()));

-- ── 6. Funktionen für die Seite ─────────────────────────────────────────────
-- Anzahl und Schnitt pro Ausgabe – nie Einzelstimmen. rating_sum erlaubt einen exakt
-- nach Stimmen gewichteten Schnitt über mehrere Ausgaben eines Gerichts.
create or replace function public.mensa_serving_stats(p_ids bigint[] default null)
returns table (
  serving_id     bigint,
  votes          integer,
  rating_sum     integer,
  avg_rating     numeric,
  filling_light  integer,
  filling_medium integer,
  filling_heavy  integer
)
language sql
stable
security definer
set search_path = ''
as $$
  select v.serving_id,
         count(*)::integer,
         sum(v.rating)::integer,
         round(avg(v.rating), 2),
         (count(*) filter (where v.filling = 1))::integer,
         (count(*) filter (where v.filling = 2))::integer,
         (count(*) filter (where v.filling = 3))::integer
    from public.mensa_votes v
   where public.mensa_is_member()
     and (p_ids is null or v.serving_id = any (p_ids))
   group by v.serving_id
$$;

-- Neues Essen eintragen: bestehendes Gericht (p_dish_id) oder neues (p_dish_name) plus
-- Ausgabe in einem Aufruf. Läuft mit den Rechten der aufrufenden Person (RLS gilt).
-- Gibt es die Ausgabe schon, wird sie zurückgegeben (existed = true) statt doppelt angelegt.
create or replace function public.mensa_add_serving(
  p_canteen_id  integer,
  p_served_on   date default null,
  p_dish_id     bigint default null,
  p_dish_name   text default null,
  p_price_cents integer default null,
  p_note        text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_day     date := coalesce(p_served_on, public.mensa_today());
  v_dish    bigint := p_dish_id;
  v_name    text := btrim(regexp_replace(coalesce(p_dish_name, ''), '\s+', ' ', 'g'));
  v_serving bigint;
  v_new_dish boolean := false;
begin
  if not public.mensa_is_member() then
    raise exception 'Nur für Mitglieder der Mensa-Gruppe' using errcode = '42501';
  end if;
  if v_day > public.mensa_today() then
    raise exception 'Das Datum liegt in der Zukunft' using errcode = '22023';
  end if;

  if v_dish is null then
    if v_name = '' then
      raise exception 'Name des Gerichts fehlt' using errcode = '22023';
    end if;
    insert into public.mensa_dishes (name) values (v_name)
      on conflict (name_key) do nothing
      returning id into v_dish;
    v_new_dish := v_dish is not null;
    if v_dish is null then
      select d.id into v_dish from public.mensa_dishes d where d.name_key = public.mensa_name_key(v_name);
    end if;
  end if;

  insert into public.mensa_servings (dish_id, canteen_id, served_on, price_cents, note)
    values (v_dish, p_canteen_id, v_day, p_price_cents, nullif(btrim(coalesce(p_note, '')), ''))
    on conflict (dish_id, canteen_id, served_on) do nothing
    returning id into v_serving;

  if v_serving is not null then
    return jsonb_build_object('serving_id', v_serving, 'dish_id', v_dish, 'existed', false, 'new_dish', v_new_dish);
  end if;

  select s.id into v_serving from public.mensa_servings s
   where s.dish_id = v_dish and s.canteen_id = p_canteen_id and s.served_on = v_day;
  return jsonb_build_object('serving_id', v_serving, 'dish_id', v_dish, 'existed', true, 'new_dish', false);
end $$;

-- Stimme abgeben oder ändern (eine pro Person). Gibt die neue Statistik der Ausgabe zurück.
create or replace function public.mensa_vote(p_serving_id bigint, p_rating integer, p_filling integer default null)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.mensa_votes (serving_id, user_id, rating, filling)
    values (p_serving_id, auth.uid(), p_rating, p_filling)
    on conflict (serving_id, user_id)
    do update set rating = excluded.rating, filling = excluded.filling;
  return (select to_jsonb(s) from public.mensa_serving_stats(array[p_serving_id]) s);
end $$;

-- Eigene Stimme zurückziehen.
create or replace function public.mensa_unvote(p_serving_id bigint)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
begin
  delete from public.mensa_votes where serving_id = p_serving_id and user_id = auth.uid();
  return (select to_jsonb(s) from public.mensa_serving_stats(array[p_serving_id]) s);
end $$;

-- Foto setzen (nach dem Upload) oder entfernen.
-- Setzen: Ersteller:in, Admin – oder jedes Mitglied, solange die Ausgabe noch kein Foto hat.
-- Entfernen: Ersteller:in oder Admin. Nur eigene, tatsächlich hochgeladene Dateien.
create or replace function public.mensa_set_photo(p_serving_id bigint, p_photo_path text, p_thumb_path text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me    uuid := auth.uid();
  v_row   public.mensa_servings;
  v_admin boolean := public.mensa_is_admin();
  v_found integer;
begin
  if not public.mensa_is_member() then
    raise exception 'Nur für Mitglieder der Mensa-Gruppe' using errcode = '42501';
  end if;
  select * into v_row from public.mensa_servings where id = p_serving_id for update;
  if not found then
    raise exception 'Eintrag nicht gefunden' using errcode = 'P0002';
  end if;
  if (p_photo_path is null) <> (p_thumb_path is null) then
    raise exception 'Foto und Vorschaubild gehören zusammen' using errcode = '22023';
  end if;

  if p_photo_path is null then
    if not (v_admin or v_row.created_by = v_me) then
      raise exception 'Nur Ersteller:in oder Admin können das Foto entfernen' using errcode = '42501';
    end if;
  else
    if not (v_admin or v_row.created_by = v_me or v_row.photo_path is null) then
      raise exception 'Dieser Eintrag hat schon ein Foto' using errcode = '42501';
    end if;
    if split_part(p_photo_path, '/', 1) <> v_me::text or split_part(p_thumb_path, '/', 1) <> v_me::text
       or p_photo_path = p_thumb_path then
      raise exception 'Ungültiger Foto-Pfad' using errcode = '42501';
    end if;
    select count(*) into v_found from storage.objects o
     where o.bucket_id = 'mensa-photos'
       and o.name in (p_photo_path, p_thumb_path)
       and coalesce(o.owner_id, o.owner::text) = v_me::text;
    if v_found <> 2 then
      raise exception 'Foto nicht gefunden – bitte erneut hochladen' using errcode = 'P0002';
    end if;
  end if;

  update public.mensa_servings set photo_path = p_photo_path, thumb_path = p_thumb_path
   where id = p_serving_id;
end $$;

-- Zwei Gerichte bewusst zusammenführen (nur Admin, nie automatisch).
create or replace function public.mensa_merge_dishes(p_keep bigint, p_drop bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.mensa_is_admin() then
    raise exception 'Nur für Admins' using errcode = '42501';
  end if;
  if p_keep = p_drop then
    raise exception 'Das ist dasselbe Gericht' using errcode = '22023';
  end if;
  if not exists (select 1 from public.mensa_dishes where id = p_keep)
     or not exists (select 1 from public.mensa_dishes where id = p_drop) then
    raise exception 'Gericht nicht gefunden' using errcode = 'P0002';
  end if;
  if exists (
    select 1 from public.mensa_servings a
      join public.mensa_servings b on a.canteen_id = b.canteen_id and a.served_on = b.served_on
     where a.dish_id = p_keep and b.dish_id = p_drop
  ) then
    raise exception 'Beide Gerichte sind am selben Tag in derselben Mensa eingetragen – bitte zuerst einen der beiden Einträge löschen.'
      using errcode = '23505';
  end if;
  update public.mensa_servings set dish_id = p_keep where dish_id = p_drop;
  delete from public.mensa_dishes where id = p_drop;
end $$;

-- Funktionen: nicht für anon, nur für angemeldete Accounts (Prüfung auf Mitgliedschaft innen).
do $$
declare f text;
begin
  foreach f in array array[
    'public.mensa_today()', 'public.mensa_name_key(text)', 'public.mensa_is_member()',
    'public.mensa_is_admin()', 'public.mensa_me()', 'public.mensa_serving_stats(bigint[])',
    'public.mensa_add_serving(integer, date, bigint, text, integer, text)',
    'public.mensa_vote(bigint, integer, integer)', 'public.mensa_unvote(bigint)',
    'public.mensa_set_photo(bigint, text, text)', 'public.mensa_merge_dishes(bigint, bigint)'
  ] loop
    execute format('revoke all on function %s from public, anon', f);
    execute format('grant execute on function %s to authenticated', f);
  end loop;
  -- Trigger-Funktionen braucht niemand direkt
  execute 'revoke all on function public.mensa_servings_guard() from public, anon, authenticated';
  execute 'revoke all on function public.mensa_votes_set_updated() from public, anon, authenticated';
  execute 'revoke all on function public.mensa_votes_touch_serving() from public, anon, authenticated';
end $$;

-- ── 7. Fotos (Storage) ──────────────────────────────────────────────────────
-- Privater Bucket: Bilder nur über zeitlich begrenzte, signierte Links.
-- Größen- und Typ-Grenze erzwingt Supabase beim Upload.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('mensa-photos', 'mensa-photos', false, 3145728, array['image/jpeg', 'image/webp'])
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Policies gelten ausschließlich für diesen Bucket. Kein UPDATE → nichts überschreibbar.
drop policy if exists "mensa photos read"   on storage.objects;
drop policy if exists "mensa photos upload" on storage.objects;
drop policy if exists "mensa photos delete" on storage.objects;

create policy "mensa photos read" on storage.objects for select to authenticated
  using (bucket_id = 'mensa-photos' and (select public.mensa_is_member()));
-- Hochladen nur in den eigenen Ordner <user-id>/…
create policy "mensa photos upload" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'mensa-photos'
    and (select public.mensa_is_member())
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
-- Löschen: eigene Dateien oder Admin
create policy "mensa photos delete" on storage.objects for delete to authenticated
  using (
    bucket_id = 'mensa-photos'
    and ((storage.foldername(name))[1] = (select auth.uid())::text or (select public.mensa_is_admin()))
  );

-- ── 8. Live-Updates ─────────────────────────────────────────────────────────
do $$
declare t text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach t in array array['mensa_servings', 'mensa_dishes'] loop
      if not exists (
        select 1 from pg_publication_tables
         where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
      ) then
        execute format('alter publication supabase_realtime add table public.%I', t);
      end if;
    end loop;
  end if;
end $$;

-- ── 9. Startdaten ───────────────────────────────────────────────────────────
insert into public.mensa_canteens (name, openmensa_id)
values ('Mensa im Neuenheimer Feld', 279)
on conflict (name) do nothing;

commit;
